---
- name: Create WordPress volume
  docker_volume:
    name: "{{ volume_wordpress }}"

- name: Start WordPress container
  register: run_wordpress
  docker_container:
    name: wordpress
    image: "{{ wordpress_img }}"
    state: started
    pull: yes
    network_mode: host
    volumes:
      - "{{ volume_wordpress }}:/bitnami/wordpress"
    ports:
      - "8080:8080"
      - "8443:8443"
    etc_hosts:
        mariadb: "{{ db_host | quote }}"
    env:
        ALLOW_EMPTY_PASSWORD: "yes"
        WORDPRESS_DATABASE_USER: "{{ db_user | quote }}"
        WORDPRESS_DATABASE_NAME: "{{ db_name | quote }}"
        WORDPRESS_DATABASE_PASSWORD: "{{ db_password | quote }}" 

- name: View WordPress status
  debug: 
    var: run_wordpress
